export const properties = [
  {
    id: "IMP-001",
    slug: "casa-condominio-imperial-park-6200",
    title: "Casa no Condomínio Imperial Park",
    purpose: "locacao",
    type: "condominio",
    city: "Redenção",
    neighborhood: "Condomínio Imperial Park",
    price: 6200,
    priceNote: "+ taxa de condomínio",
    bedrooms: 3,
    suites: 3,
    bathrooms: null,
    parking: null,
    builtArea: null,
    landArea: null,
    shortDescription: "Casa de alto padrão com três suítes em condomínio fechado.",
    fullDescription:
      "Uma opção residencial no Condomínio Imperial Park, com três suítes e perfil de alto padrão. A localização divulgada é aproximada; disponibilidade, taxa de condomínio e demais condições devem ser confirmadas no atendimento.",
    features: ["Condomínio fechado", "3 suítes", "Alto padrão"],
    status: "A confirmar",
    featured: true,
    financeable: null,
    furnished: null,
    mainImage: {
      label: "Imagem aguardando liberação para publicação",
      tone: "forest",
    },
    gallery: [
      {
        label: "Imagem aguardando liberação para publicação",
        tone: "forest",
      },
    ],
    publishedAt: "2026-07-29",
  },
  {
    id: "IMP-002",
    slug: "casa-imperial-park-310m2",
    title: "Casa no Imperial Park · 310 m²",
    purpose: "locacao",
    type: "condominio",
    city: "Redenção",
    neighborhood: "Condomínio Imperial Park",
    price: 8000,
    priceNote: "+ taxa de condomínio",
    bedrooms: 4,
    suites: 4,
    bathrooms: null,
    parking: null,
    builtArea: 310,
    landArea: null,
    shortDescription: "Quatro suítes, cozinha completa e área de lazer com churrasqueira.",
    fullDescription:
      "Casa com 310 m² de área construída, quatro suítes, lavabo, cozinha completa e ambientes preparados para uma rotina confortável. A disponibilidade, a taxa de condomínio e as condições da locação devem ser confirmadas.",
    features: [
      "4 suítes",
      "Lavabo",
      "Ar-condicionado",
      "Cortinas instaladas",
      "Cozinha completa",
      "Área gourmet",
      "Churrasqueira",
      "Lavanderia",
      "Despensa",
      "Energia solar",
    ],
    status: "A confirmar",
    featured: true,
    financeable: null,
    furnished: null,
    mainImage: {
      label: "Imagem aguardando liberação para publicação",
      tone: "sage",
    },
    gallery: [
      {
        label: "Imagem aguardando liberação para publicação",
        tone: "sage",
      },
    ],
    publishedAt: "2026-07-29",
  },
  {
    id: "IMP-003",
    slug: "casa-imperial-park-planejados",
    title: "Casa no Imperial Park · Planejados",
    purpose: "locacao",
    type: "condominio",
    city: "Redenção",
    neighborhood: "Condomínio Imperial Park",
    price: 7000,
    priceNote: "+ taxa de condomínio",
    bedrooms: 4,
    suites: 4,
    bathrooms: null,
    parking: 4,
    builtArea: null,
    landArea: null,
    shortDescription: "Quatro suítes, ambientes planejados e garagem para quatro carros.",
    fullDescription:
      "Casa com quatro suítes e móveis planejados em diferentes ambientes, incluindo sala e espaço gourmet. Conta ainda com churrasqueira, lavanderia, despensa, depósito e garagem para quatro carros. Consulte disponibilidade e condições.",
    features: [
      "4 suítes",
      "Lavabo",
      "Móveis planejados",
      "Área gourmet",
      "Churrasqueira",
      "Lavanderia",
      "Despensa",
      "Depósito",
      "Garagem para 4 carros",
    ],
    status: "A confirmar",
    featured: true,
    financeable: null,
    furnished: null,
    mainImage: {
      label: "Imagem aguardando liberação para publicação",
      tone: "clay",
    },
    gallery: [
      {
        label: "Imagem aguardando liberação para publicação",
        tone: "clay",
      },
    ],
    publishedAt: "2026-07-29",
  },
  {
    id: "NAS-001",
    slug: "imovel-casas-nasta-jardim-cumaru",
    title: "Imóvel nas Casas Nasta",
    purpose: "locacao",
    type: "casa",
    city: "Redenção",
    neighborhood: "Casas Nasta · Jardim Cumaru",
    price: 2200,
    priceNote: "a partir de",
    bedrooms: null,
    suites: null,
    bathrooms: null,
    parking: null,
    builtArea: null,
    landArea: null,
    shortDescription: "Duas configurações de locação para adaptar o imóvel à sua rotina.",
    fullDescription:
      "Imóvel para locação no Jardim Cumaru. O valor parte de R$ 2.200 sem cooktop, armário inferior da cozinha e guarda-roupa da suíte, ou R$ 2.500 com esses itens planejados. Confirme a configuração disponível no atendimento.",
    features: ["Opção com itens planejados", "Jardim Cumaru"],
    status: "A confirmar",
    featured: false,
    financeable: null,
    furnished: false,
    mainImage: { label: "Foto a ser adicionada", tone: "linen" },
    gallery: [{ label: "Foto a ser adicionada", tone: "linen" }],
    publishedAt: "2026-07-29",
  },
  {
    id: "VEN-001",
    slug: "oportunidade-venda-350-mil",
    title: "Oportunidade de R$ 350 mil",
    purpose: "venda",
    type: "casa",
    city: "Redenção",
    neighborhood: "Localização sob consulta",
    price: 350000,
    priceNote: "",
    bedrooms: null,
    suites: null,
    bathrooms: null,
    parking: null,
    builtArea: null,
    landArea: null,
    shortDescription: "Imóvel à venda com possibilidades de negociação a consultar.",
    fullDescription:
      "Oportunidade de venda com valor de referência de R$ 350 mil. Há possibilidades de negociação registradas no catálogo, que devem ser explicadas e confirmadas diretamente no atendimento antes de qualquer decisão.",
    features: ["Possibilidades de negociação", "Atendimento direto"],
    status: "A confirmar",
    featured: false,
    financeable: null,
    furnished: null,
    mainImage: {
      label: "Imagem aguardando liberação para publicação",
      tone: "earth",
    },
    gallery: [
      {
        label: "Imagem aguardando liberação para publicação",
        tone: "earth",
      },
    ],
    publishedAt: "2026-07-29",
  },
  {
    id: "BUR-001",
    slug: "casa-park-dos-buritis-i",
    title: "Casa no Park dos Buritis I",
    purpose: "locacao",
    type: "casa",
    city: "Redenção",
    neighborhood: "Park dos Buritis I",
    price: 3000,
    priceNote: "",
    bedrooms: null,
    suites: null,
    bathrooms: null,
    parking: null,
    builtArea: null,
    landArea: 225,
    shortDescription: "Casa residencial em terreno de 225 m² no Park dos Buritis I.",
    fullDescription:
      "Casa para locação residencial no Park dos Buritis I, em terreno de 225 m². Por privacidade, o endereço completo não é exibido. Disponibilidade e condições atuais devem ser confirmadas no atendimento.",
    features: ["Terreno de 225 m²", "Uso residencial"],
    status: "A confirmar",
    featured: false,
    financeable: null,
    furnished: null,
    mainImage: { label: "Foto a ser adicionada", tone: "olive" },
    gallery: [{ label: "Foto a ser adicionada", tone: "olive" }],
    publishedAt: "2026-07-29",
  },
  {
    id: "COM-001",
    slug: "sala-comercial-galeria-sanches",
    title: "Sala comercial na Galeria Sanches",
    purpose: "locacao",
    type: "sala",
    city: "Redenção",
    neighborhood: "Galeria Sanches",
    price: 3500,
    priceNote: "",
    bedrooms: 0,
    suites: 0,
    bathrooms: null,
    parking: null,
    builtArea: null,
    landArea: null,
    shortDescription: "Sala comercial compacta em ponto de referência conhecido.",
    fullDescription:
      "Sala comercial para locação na Galeria Sanches, ao lado da Nosso Lar. Espaço de perfil compacto, indicado para diferentes atividades de atendimento e varejo. Consulte disponibilidade e condições.",
    features: ["Galeria comercial", "Ponto de referência próximo", "Uso comercial"],
    status: "A confirmar",
    featured: false,
    financeable: null,
    furnished: null,
    mainImage: { label: "Foto a ser adicionada", tone: "graphite" },
    gallery: [{ label: "Foto a ser adicionada", tone: "graphite" }],
    publishedAt: "2026-07-29",
  },
];

export const typeLabels = {
  casa: "Casa",
  apartamento: "Apartamento",
  lote: "Lote",
  sala: "Sala comercial",
  condominio: "Imóvel em condomínio",
};

export const purposeLabels = {
  venda: "Comprar",
  locacao: "Alugar",
};
