export const properties = [
  {
    id: "IMP-001",
    slug: "casa-condominio-imperial-park-6200",
    title: "Casa no CondomÃ­nio Imperial Park",
    purpose: "locacao",
    type: "condominio",
    city: "RedenÃ§Ã£o",
    neighborhood: "CondomÃ­nio Imperial Park",
    price: 6200,
    priceNote: "+ taxa de condomÃ­nio",
    bedrooms: 3,
    suites: 3,
    bathrooms: null,
    parking: null,
    builtArea: null,
    landArea: null,
    shortDescription: "Casa de alto padrÃ£o com trÃªs suÃ­tes em condomÃ­nio fechado.",
    fullDescription:
      "Uma opÃ§Ã£o residencial no CondomÃ­nio Imperial Park, com trÃªs suÃ­tes e perfil de alto padrÃ£o. A localizaÃ§Ã£o divulgada Ã© aproximada; disponibilidade, taxa de condomÃ­nio e demais condiÃ§Ãµes devem ser confirmadas no atendimento.",
    features: ["CondomÃ­nio fechado", "3 suÃ­tes", "Alto padrÃ£o"],
    status: "Arquivado",
    featured: true,
    financeable: null,
    furnished: null,
    mainImage: {
      label: "Imagem aguardando liberaÃ§Ã£o para publicaÃ§Ã£o",
      tone: "forest",
    },
    gallery: [
      {
        label: "Imagem aguardando liberaÃ§Ã£o para publicaÃ§Ã£o",
        tone: "forest",
      },
    ],
    publishedAt: "2026-07-29",
  },
  {
    id: "IMP-002",
    slug: "casa-imperial-park-310m2",
    title: "Casa no Imperial Park Â· 310 mÂ²",
    purpose: "locacao",
    type: "condominio",
    city: "RedenÃ§Ã£o",
    neighborhood: "CondomÃ­nio Imperial Park",
    price: 8000,
    priceNote: "+ taxa de condomÃ­nio",
    bedrooms: 4,
    suites: 4,
    bathrooms: null,
    parking: null,
    builtArea: 310,
    landArea: null,
    shortDescription: "Quatro suÃ­tes, cozinha completa e Ã¡rea de lazer com churrasqueira.",
    fullDescription:
      "Casa com 310 mÂ² de Ã¡rea construÃ­da, quatro suÃ­tes, lavabo, cozinha completa e ambientes preparados para uma rotina confortÃ¡vel. A disponibilidade, a taxa de condomÃ­nio e as condiÃ§Ãµes da locaÃ§Ã£o devem ser confirmadas.",
    features: [
      "4 suÃ­tes",
      "Lavabo",
      "Ar-condicionado",
      "Cortinas instaladas",
      "Cozinha completa",
      "Ãrea gourmet",
      "Churrasqueira",
      "Lavanderia",
      "Despensa",
      "Energia solar",
    ],
    status: "Indisponível",
    featured: true,
    financeable: null,
    furnished: null,
    mainImage: {
      label: "Imagem aguardando liberaÃ§Ã£o para publicaÃ§Ã£o",
      tone: "sage",
    },
    gallery: [
      {
        label: "Imagem aguardando liberaÃ§Ã£o para publicaÃ§Ã£o",
        tone: "sage",
      },
    ],
    publishedAt: "2026-07-29",
  },
  {
    id: "IMP-003",
    slug: "casa-imperial-park-planejados",
    title: "Casa no Imperial Park Â· Planejados",
    purpose: "locacao",
    type: "condominio",
    city: "RedenÃ§Ã£o",
    neighborhood: "CondomÃ­nio Imperial Park",
    price: 7000,
    priceNote: "+ taxa de condomÃ­nio",
    bedrooms: 4,
    suites: 4,
    bathrooms: null,
    parking: 4,
    builtArea: null,
    landArea: null,
    shortDescription: "Quatro suÃ­tes, ambientes planejados e garagem para quatro carros.",
    fullDescription:
      "Casa com quatro suÃ­tes e mÃ³veis planejados em diferentes ambientes, incluindo sala e espaÃ§o gourmet. Conta ainda com churrasqueira, lavanderia, despensa, depÃ³sito e garagem para quatro carros. Consulte disponibilidade e condiÃ§Ãµes.",
    features: [
      "4 suÃ­tes",
      "Lavabo",
      "MÃ³veis planejados",
      "Ãrea gourmet",
      "Churrasqueira",
      "Lavanderia",
      "Despensa",
      "DepÃ³sito",
      "Garagem para 4 carros",
    ],
    status: "Arquivado",
    featured: true,
    financeable: null,
    furnished: null,
    mainImage: {
      label: "Imagem aguardando liberaÃ§Ã£o para publicaÃ§Ã£o",
      tone: "clay",
    },
    gallery: [
      {
        label: "Imagem aguardando liberaÃ§Ã£o para publicaÃ§Ã£o",
        tone: "clay",
      },
    ],
    publishedAt: "2026-07-29",
  },
  {
    id: "NAS-001",
    slug: "imovel-casas-nasta-jardim-cumaru",
    title: "ImÃ³vel nas Casas Nasta",
    purpose: "locacao",
    type: "casa",
    city: "RedenÃ§Ã£o",
    neighborhood: "Casas Nasta Â· Jardim Cumaru",
    price: 2200,
    priceNote: "a partir de",
    bedrooms: null,
    suites: null,
    bathrooms: null,
    parking: null,
    builtArea: null,
    landArea: null,
    shortDescription: "Duas configuraÃ§Ãµes de locaÃ§Ã£o para adaptar o imÃ³vel Ã  sua rotina.",
    fullDescription:
      "ImÃ³vel para locaÃ§Ã£o no Jardim Cumaru. O valor parte de R$ 2.200 sem cooktop, armÃ¡rio inferior da cozinha e guarda-roupa da suÃ­te, ou R$ 2.500 com esses itens planejados. Confirme a configuraÃ§Ã£o disponÃ­vel no atendimento.",
    features: ["OpÃ§Ã£o com itens planejados", "Jardim Cumaru"],
    status: "Em preparação",
    featured: false,
    financeable: null,
    furnished: false,
    mainImage: { label: "Foto a ser adicionada", tone: "linen" },
    gallery: [{ label: "Foto a ser adicionada", tone: "linen" }],
    publishedAt: "2026-07-29",
  },
  {
    id: "VEN-001",
    slug: "oportunidade-venda-350-mil",
    title: "Oportunidade de R$ 350 mil",
    purpose: "venda",
    type: "casa",
    city: "RedenÃ§Ã£o",
    neighborhood: "LocalizaÃ§Ã£o sob consulta",
    price: 350000,
    priceNote: "",
    bedrooms: null,
    suites: null,
    bathrooms: null,
    parking: null,
    builtArea: null,
    landArea: null,
    shortDescription: "ImÃ³vel Ã  venda com possibilidades de negociaÃ§Ã£o a consultar.",
    fullDescription:
      "Oportunidade de venda com valor de referÃªncia de R$ 350 mil. HÃ¡ possibilidades de negociaÃ§Ã£o registradas no catÃ¡logo, que devem ser explicadas e confirmadas diretamente no atendimento antes de qualquer decisÃ£o.",
    features: ["Possibilidades de negociaÃ§Ã£o", "Atendimento direto"],
    status: "Arquivado",
    featured: false,
    financeable: null,
    furnished: null,
    mainImage: {
      label: "Imagem aguardando liberaÃ§Ã£o para publicaÃ§Ã£o",
      tone: "earth",
    },
    gallery: [
      {
        label: "Imagem aguardando liberaÃ§Ã£o para publicaÃ§Ã£o",
        tone: "earth",
      },
    ],
    publishedAt: "2026-07-29",
  },
  {
    id: "BUR-001",
    slug: "casa-park-dos-buritis-i",
    title: "Casa no Park dos Buritis I",
    purpose: "locacao",
    type: "casa",
    city: "RedenÃ§Ã£o",
    neighborhood: "Park dos Buritis I",
    price: 3000,
    priceNote: "",
    bedrooms: null,
    suites: null,
    bathrooms: null,
    parking: null,
    builtArea: null,
    landArea: 225,
    shortDescription: "Casa residencial em terreno de 225 mÂ² no Park dos Buritis I.",
    fullDescription:
      "Casa para locaÃ§Ã£o residencial no Park dos Buritis I, em terreno de 225 mÂ². Por privacidade, o endereÃ§o completo nÃ£o Ã© exibido. Disponibilidade e condiÃ§Ãµes atuais devem ser confirmadas no atendimento.",
    features: ["Terreno de 225 mÂ²", "Uso residencial"],
    status: "Indisponível",
    featured: false,
    financeable: null,
    furnished: null,
    mainImage: { label: "Foto a ser adicionada", tone: "olive" },
    gallery: [{ label: "Foto a ser adicionada", tone: "olive" }],
    publishedAt: "2026-07-29",
  },
  {
    id: "COM-001",
    slug: "sala-comercial-galeria-sanches",
    title: "Sala comercial na Galeria Sanches",
    purpose: "locacao",
    type: "sala",
    city: "RedenÃ§Ã£o",
    neighborhood: "Galeria Sanches",
    price: 3500,
    priceNote: "",
    bedrooms: 0,
    suites: 0,
    bathrooms: null,
    parking: null,
    builtArea: null,
    landArea: null,
    shortDescription: "Sala comercial compacta em ponto de referÃªncia conhecido.",
    fullDescription:
      "Sala comercial para locaÃ§Ã£o na Galeria Sanches, ao lado da Nosso Lar. EspaÃ§o de perfil compacto, indicado para diferentes atividades de atendimento e varejo. Consulte disponibilidade e condiÃ§Ãµes.",
    features: ["Galeria comercial", "Ponto de referÃªncia prÃ³ximo", "Uso comercial"],
    status: "Arquivado",
    featured: false,
    financeable: null,
    furnished: null,
    mainImage: { label: "Foto a ser adicionada", tone: "graphite" },
    gallery: [{ label: "Foto a ser adicionada", tone: "graphite" }],
    publishedAt: "2026-07-29",
  },
];

export const typeLabels = {
  casa: "Casa",
  apartamento: "Apartamento",
  lote: "Lote",
  sala: "Sala comercial",
  condominio: "ImÃ³vel em condomÃ­nio",
};

export const purposeLabels = {
  venda: "Comprar",
  locacao: "Alugar",
};

