import { propertyMedia } from "./propertyMedia.js";

const listingRecords = [
  {
    "id": "REF-023",
    "idRef": "023",
    "slug": "casa-alto-padrao-park-dos-buritis-i-ref-023",
    "title": "Casa de alto padrão no Park dos Buritis I",
    "purpose": "venda",
    "type": "casa",
    "city": "Redenção",
    "neighborhood": "Park dos Buritis I",
    "publicLocation": "Park dos Buritis I, Redenção",
    "price": 1800000,
    "priceOnRequest": false,
    "priceNote": null,
    "condominiumFee": null,
    "fees": [],
    "conditions": [],
    "bedrooms": null,
    "suites": 3,
    "bathrooms": null,
    "lavabos": null,
    "parking": null,
    "builtArea": 227,
    "landArea": 450,
    "landDimensions": null,
    "status": "Disponibilidade sob consulta",
    "featured": true,
    "shortDescription": "Residência de alto padrão com três suítes, piscina e área social integrada.",
    "fullDescription": "Residência contemporânea de alto padrão com três suítes e ambientes planejados para integração e convivência. A área social se conecta à piscina e ao paisagismo, enquanto a cozinha gourmet conta com ilha central e marcenaria planejada. O imóvel possui 227 m² construídos em um lote de 450 m², com aproximadamente 117 m² de área permeável.",
    "features": [
      "3 suítes",
      "227 m² construídos",
      "Lote de 450 m²",
      "Aproximadamente 117 m² de área permeável",
      "Área social integrada",
      "Grandes planos de vidro"
    ],
    "amenities": [
      "Piscina",
      "Paisagismo",
      "Cozinha gourmet planejada",
      "Ilha central",
      "Ar-condicionado nos dormitórios"
    ],
    "documents": [],
    "financeable": null,
    "furnished": null,
    "publishedAt": "2026-08-08"
  },
  {
    "id": "REF-026",
    "idRef": "026",
    "slug": "casa-piscina-park-dos-buritis-iii-ref-026",
    "title": "Casa Marbella",
    "purpose": "venda",
    "type": "casa",
    "city": "Redenção",
    "neighborhood": "Park dos Buritis III",
    "publicLocation": "Park dos Buritis III, Redenção",
    "price": 1000000,
    "priceOnRequest": false,
    "priceNote": null,
    "condominiumFee": null,
    "fees": [],
    "conditions": [],
    "bedrooms": 1,
    "suites": 2,
    "bathrooms": null,
    "lavabos": null,
    "parking": null,
    "builtArea": null,
    "landArea": null,
    "landDimensions": null,
    "status": "Disponível",
    "featured": true,
    "shortDescription": "Casa com duas suítes, um quarto e área de lazer completa com piscina.",
    "fullDescription": "Casa com duas suítes, sendo uma master, além de um quarto, banheiro social, cozinha e lavanderia. A área de lazer reúne piscina com cascata, espaço de churrasqueira e banheiro de apoio. A integração entre o espaço gourmet, as esquadrias de vidro e a área externa cria uma configuração agradável para convivência.",
    "features": [
      "2 suítes, sendo 1 master",
      "1 quarto",
      "Banheiro social",
      "Banheiro na área de lazer",
      "Cozinha",
      "Lavanderia",
      "Canil"
    ],
    "amenities": [
      "Piscina com cascata",
      "Espaço de churrasqueira",
      "Área gourmet",
      "Bancada com cooktop",
      "Marcenaria planejada na área gourmet"
    ],
    "documents": [],
    "financeable": null,
    "furnished": null,
    "publishedAt": "2026-08-08"
  },
  {
    "id": "REF-035",
    "idRef": "035",
    "slug": "casa-buriti-3-rua-4-ref-035",
    "title": "Casa Lisboa",
    "purpose": "venda",
    "type": "casa",
    "city": "Redenção",
    "neighborhood": "Buriti 3",
    "publicLocation": "Rua 4, Buriti 3, Redenção",
    "price": 400000,
    "priceOnRequest": false,
    "priceNote": "R$ 400.000 quitada ou R$ 360.000 assumindo o saldo devedor",
    "condominiumFee": null,
    "fees": [],
    "conditions": [
      "R$ 400.000 com o imóvel quitado",
      "R$ 360.000 com assunção do saldo devedor"
    ],
    "bedrooms": null,
    "suites": 2,
    "bathrooms": null,
    "lavabos": null,
    "parking": null,
    "builtArea": null,
    "landArea": null,
    "landDimensions": null,
    "status": "Disponível",
    "featured": false,
    "shortDescription": "Casa com duas suítes confirmadas e duas condições de negociação.",
    "fullDescription": "Casa de proposta prática e contemporânea, com duas suítes confirmadas e circulação lateral coberta. A cozinha possui bancada escura, cooktop e revestimento decorativo, enquanto os banheiros das suítes contam com box e acabamentos claros. A área de serviço é coberta e possui tanque.",
    "features": [
      "2 suítes confirmadas",
      "Circulação lateral coberta",
      "Cozinha com bancada escura",
      "Cooktop",
      "Área de serviço coberta"
    ],
    "amenities": [
      "Box nos banheiros das suítes"
    ],
    "documents": [],
    "financeable": null,
    "furnished": null,
    "publishedAt": "2026-08-08"
  },
  {
    "id": "REF-029",
    "idRef": "029",
    "slug": "casa-setor-marechal-rondon-ref-029",
    "title": "Casa à venda no Setor Marechal Rondon",
    "purpose": "venda",
    "type": "casa",
    "city": "Redenção",
    "neighborhood": "Setor Marechal Rondon",
    "publicLocation": "Setor Marechal Rondon, Redenção",
    "price": 430000,
    "priceOnRequest": false,
    "priceNote": null,
    "condominiumFee": null,
    "fees": [],
    "conditions": [
      "Imóvel pronto para financiamento"
    ],
    "bedrooms": 2,
    "suites": 1,
    "bathrooms": null,
    "lavabos": null,
    "parking": null,
    "builtArea": 110,
    "landArea": null,
    "landDimensions": "aprox. 5,5 × 40 m",
    "status": "Disponibilidade sob consulta",
    "featured": false,
    "shortDescription": "Casa averbada com suíte, closet e 110 m² construídos.",
    "fullDescription": "Casa com dois quartos e uma suíte com closet, além de sala e cozinha integradas. Possui 110 m² construídos, garagem e quintais na frente e nos fundos. O imóvel conta com poço semiartesiano, cerca elétrica e portão eletrônico, está averbado e pronto para financiamento.",
    "features": [
      "2 quartos",
      "1 suíte com closet",
      "110 m² construídos",
      "Sala e cozinha integradas",
      "Garagem",
      "Quintal na frente e nos fundos",
      "Lavanderia"
    ],
    "amenities": [
      "Poço semiartesiano",
      "Cerca elétrica",
      "Portão eletrônico"
    ],
    "documents": [
      "Imóvel averbado"
    ],
    "financeable": true,
    "furnished": null,
    "publishedAt": "2026-08-08"
  },
  {
    "id": "REF-025",
    "idRef": "025",
    "slug": "casa-avenida-jose-carrion-ref-025",
    "title": "Casa para locação na Avenida José Carrion",
    "purpose": "locacao",
    "type": "casa",
    "city": "Redenção",
    "neighborhood": null,
    "publicLocation": "Avenida José Carrion, Redenção",
    "price": 4000,
    "priceOnRequest": false,
    "priceNote": "Negociável a R$ 3.500",
    "condominiumFee": null,
    "fees": [],
    "conditions": [
      "Valor negociável a R$ 3.500"
    ],
    "bedrooms": null,
    "suites": null,
    "bathrooms": null,
    "lavabos": null,
    "parking": null,
    "builtArea": null,
    "landArea": null,
    "landDimensions": null,
    "status": "Disponibilidade sob consulta",
    "featured": false,
    "shortDescription": "Casa térrea com garagem frontal ampla e áreas cobertas.",
    "fullDescription": "Casa térrea com perfil tradicional, garagem frontal ampla e áreas cobertas de apoio. Os ambientes apresentam forro e portas de madeira, passagens arqueadas e pisos claros. A cozinha possui bancada de desenho arredondado, e a área posterior reúne pátio e espaço coberto de serviço.",
    "features": [
      "Casa térrea",
      "Garagem frontal ampla",
      "Áreas cobertas",
      "Forro de madeira",
      "Cozinha com bancada",
      "Área de serviço"
    ],
    "amenities": [
      "Banheiros com box de vidro"
    ],
    "documents": [],
    "financeable": null,
    "furnished": null,
    "publishedAt": "2026-08-08"
  },
  {
    "id": "REF-028",
    "idRef": "028",
    "slug": "casa-condominio-cedro-ref-028",
    "title": "Casa para locação no Condomínio Cedro",
    "purpose": "locacao",
    "type": "casa",
    "city": "Redenção",
    "neighborhood": "Condomínio Cedro",
    "publicLocation": "Condomínio Cedro, Redenção",
    "price": 3200,
    "priceOnRequest": false,
    "priceNote": "+ condomínio de R$ 810",
    "condominiumFee": 810,
    "fees": [],
    "conditions": [
      "Há registro de desconto de R$ 61 sujeito à condição a confirmar no atendimento"
    ],
    "bedrooms": null,
    "suites": 2,
    "bathrooms": null,
    "lavabos": null,
    "parking": null,
    "builtArea": null,
    "landArea": null,
    "landDimensions": null,
    "status": "Disponibilidade sob consulta",
    "featured": false,
    "shortDescription": "Casa com duas suítes climatizadas e área gourmet com churrasqueira.",
    "fullDescription": "Casa com duas suítes climatizadas, sala em conceito aberto, sala de TV e banheiro social. A cozinha possui marcenaria planejada clara e bancada escura. A área gourmet coberta, com churrasqueira e armários de apoio, complementa a lavanderia e a circulação lateral.",
    "features": [
      "2 suítes com ar-condicionado",
      "Sala em conceito aberto",
      "Sala de TV",
      "Banheiro social",
      "Cozinha planejada",
      "Lavanderia",
      "Circulação lateral"
    ],
    "amenities": [
      "Área gourmet coberta",
      "Churrasqueira",
      "Armários de apoio"
    ],
    "documents": [],
    "financeable": null,
    "furnished": null,
    "publishedAt": "2026-08-08"
  },
  {
    "id": "REF-033",
    "idRef": "033",
    "slug": "casa-casas-nasta-jardim-ariane-ref-033",
    "title": "Casa Lucca",
    "purpose": "locacao",
    "type": "casa",
    "city": "Redenção",
    "neighborhood": "Jardim Ariane",
    "publicLocation": "Casas Nasta, Jardim Ariane, Redenção",
    "price": 2200,
    "priceOnRequest": false,
    "priceNote": "R$ 2.200 sem planejados ou R$ 2.500 com itens planejados",
    "condominiumFee": null,
    "fees": [],
    "conditions": [
      "R$ 2.200 sem os itens planejados",
      "R$ 2.500 com cooktop, armário inferior da cozinha e guarda-roupa da suíte"
    ],
    "bedrooms": 1,
    "suites": 1,
    "bathrooms": null,
    "lavabos": null,
    "parking": null,
    "builtArea": null,
    "landArea": null,
    "landDimensions": null,
    "status": "Disponível",
    "featured": false,
    "shortDescription": "Casa recente com uma suíte, um quarto e duas opções de locação.",
    "fullDescription": "Casa de configuração compacta e funcional, com uma suíte, um quarto e banheiro social. A cozinha possui bancada extensa, e a área externa reúne corredor lateral, pequeno trecho gramado e serviço coberto com tanque. A locação pode ser contratada sem os itens planejados ou com cooktop, armário inferior da cozinha e guarda-roupa da suíte.",
    "features": [
      "1 suíte",
      "1 quarto",
      "Banheiro social",
      "Cozinha com bancada",
      "Área de serviço coberta",
      "Corredor lateral",
      "Pequeno quintal gramado"
    ],
    "amenities": [
      "Opção com itens planejados"
    ],
    "documents": [],
    "financeable": null,
    "furnished": null,
    "publishedAt": "2026-08-08"
  },
  {
    "id": "REF-034",
    "idRef": "034",
    "slug": "casa-energia-solar-centro-ref-034",
    "title": "Casa Valência",
    "purpose": "locacao",
    "type": "casa",
    "city": "Redenção",
    "neighborhood": "Centro",
    "publicLocation": "Centro, Redenção",
    "price": 7500,
    "priceOnRequest": false,
    "priceNote": null,
    "condominiumFee": null,
    "fees": [],
    "conditions": [
      "Móveis podem ser negociados no fechamento"
    ],
    "bedrooms": null,
    "suites": null,
    "bathrooms": null,
    "lavabos": null,
    "parking": null,
    "builtArea": null,
    "landArea": null,
    "landDimensions": null,
    "status": "Disponível",
    "featured": false,
    "shortDescription": "Residência ampla no Centro, com energia solar e grande área frontal coberta.",
    "fullDescription": "Residência térrea de porte amplo, com energia solar e extensa área frontal coberta, adequada para garagem e permanência. A madeira está presente na cobertura, nas portas e em detalhes internos, enquanto a vegetação suaviza a entrada. Os móveis podem ser negociados no fechamento.",
    "features": [
      "Residência térrea",
      "Ampla área frontal coberta",
      "Garagem coberta",
      "Áreas de apoio e serviço",
      "Detalhes em madeira"
    ],
    "amenities": [
      "Energia solar",
      "Móveis negociáveis",
      "Vegetação na área frontal"
    ],
    "documents": [],
    "financeable": null,
    "furnished": null,
    "publishedAt": "2026-08-08"
  },
  {
    "id": "REF-036",
    "idRef": "036",
    "slug": "casa-tres-suites-park-imperial-ref-036",
    "title": "Casa Vicenza",
    "purpose": "locacao",
    "type": "casa",
    "city": "Redenção",
    "neighborhood": "Park Imperial",
    "publicLocation": "Park Imperial, Redenção",
    "price": 6200,
    "priceOnRequest": false,
    "priceNote": "+ taxa",
    "condominiumFee": null,
    "fees": [
      "Taxa adicional com valor não informado"
    ],
    "conditions": [],
    "bedrooms": null,
    "suites": 3,
    "bathrooms": null,
    "lavabos": null,
    "parking": 2,
    "builtArea": null,
    "landArea": null,
    "landDimensions": null,
    "status": "Disponível",
    "featured": false,
    "shortDescription": "Casa contemporânea com três suítes, duas vagas e cozinha planejada.",
    "fullDescription": "Casa contemporânea com três suítes, duas vagas e ambientes de base clara. A cozinha combina marcenaria planejada, bancada escura e revestimento geométrico. O imóvel também conta com lavanderia e área externa com pergolado de madeira.",
    "features": [
      "3 suítes",
      "2 vagas",
      "Cozinha planejada",
      "Lavanderia",
      "Área externa",
      "Pergolado de madeira",
      "Armários planejados"
    ],
    "amenities": [
      "Banheiros com box de vidro"
    ],
    "documents": [],
    "financeable": null,
    "furnished": null,
    "publishedAt": "2026-08-08"
  },
  {
    "id": "REF-037",
    "idRef": "037",
    "slug": "casa-quatro-suites-condominio-imperial-ref-037",
    "title": "Casa Milão",
    "purpose": "locacao",
    "type": "casa",
    "city": "Redenção",
    "neighborhood": "Condomínio Imperial",
    "publicLocation": "Condomínio Imperial, Redenção",
    "price": 8000,
    "priceOnRequest": false,
    "priceNote": "+ taxa de condomínio",
    "condominiumFee": null,
    "fees": [
      "Taxa de condomínio adicional, com valor não informado"
    ],
    "conditions": [],
    "bedrooms": null,
    "suites": 4,
    "bathrooms": null,
    "lavabos": 1,
    "parking": null,
    "builtArea": 310,
    "landArea": null,
    "landDimensions": null,
    "status": "Disponível",
    "featured": true,
    "shortDescription": "Residência de 310 m² com quatro suítes, energia solar e área gourmet.",
    "fullDescription": "Residência de 310 m² com quatro suítes, lavabo e ambientes sociais amplos. A cozinha é planejada e completa, e a área de convivência inclui churrasqueira. O imóvel também possui lavanderia, despensa, energia solar e ar-condicionado nos dormitórios.",
    "features": [
      "310 m²",
      "4 suítes",
      "1 lavabo",
      "Cozinha completa e planejada",
      "Lavanderia",
      "Despensa",
      "Ambientes sociais amplos"
    ],
    "amenities": [
      "Churrasqueira",
      "Energia solar",
      "Ar-condicionado nos dormitórios",
      "Paisagismo"
    ],
    "documents": [],
    "financeable": null,
    "furnished": null,
    "publishedAt": "2026-08-08"
  },
  {
    "id": "REF-017-103",
    "idRef": "017-103",
    "slug": "apartamento-edificio-soberano-unidade-103-ref-017",
    "title": "Apartamento 103 no Edifício Soberano",
    "purpose": "locacao",
    "type": "apartamento",
    "city": "Redenção",
    "neighborhood": null,
    "publicLocation": "Próximo à FESAR, Redenção",
    "price": 1600,
    "priceOnRequest": false,
    "priceNote": "Sem mobília",
    "condominiumFee": null,
    "fees": [],
    "conditions": [
      "Disponibilidade deve ser confirmada no atendimento"
    ],
    "bedrooms": null,
    "suites": null,
    "bathrooms": null,
    "lavabos": null,
    "parking": null,
    "builtArea": null,
    "landArea": null,
    "landDimensions": null,
    "status": "Disponibilidade sob consulta",
    "featured": false,
    "shortDescription": "Apartamento sem mobília, com cozinha compacta e área de serviço.",
    "fullDescription": "Apartamento sem mobília no Edifício Soberano, próximo à FESAR. A unidade possui cozinha compacta com bancada clara e armários inferiores, além de tanque na área de serviço. Há ar-condicionado em um dos dormitórios; a configuração total deve ser confirmada no atendimento.",
    "features": [
      "Sem mobília",
      "Cozinha compacta",
      "Armários inferiores na cozinha",
      "Área de serviço com tanque"
    ],
    "amenities": [
      "Ar-condicionado em um dormitório"
    ],
    "documents": [],
    "financeable": null,
    "furnished": null,
    "publishedAt": "2026-08-08"
  },
  {
    "id": "REF-017-203",
    "idRef": "017-203",
    "slug": "apartamento-edificio-soberano-unidade-203-ref-017",
    "title": "Apartamento 203 no Edifício Soberano",
    "purpose": "locacao",
    "type": "apartamento",
    "city": "Redenção",
    "neighborhood": null,
    "publicLocation": "Próximo à FESAR, Redenção",
    "price": 1800,
    "priceOnRequest": false,
    "priceNote": "Semi mobiliado",
    "condominiumFee": null,
    "fees": [],
    "conditions": [
      "Itens inclusos e disponibilidade devem ser confirmados no atendimento"
    ],
    "bedrooms": 1,
    "suites": null,
    "bathrooms": null,
    "lavabos": null,
    "parking": null,
    "builtArea": null,
    "landArea": null,
    "landDimensions": null,
    "status": "Disponibilidade sob consulta",
    "featured": false,
    "shortDescription": "Apartamento de um dormitório, semi mobiliado e com marcenaria planejada.",
    "fullDescription": "Apartamento semi mobiliado no Edifício Soberano, próximo à FESAR. A unidade possui um dormitório e apresenta marcenaria planejada, incluindo guarda-roupa. A relação exata dos itens inclusos deve ser confirmada no atendimento.",
    "features": [
      "1 dormitório",
      "Semi mobiliado",
      "Marcenaria planejada",
      "Guarda-roupa"
    ],
    "amenities": [],
    "documents": [],
    "financeable": null,
    "furnished": null,
    "publishedAt": "2026-08-08"
  },
  {
    "id": "REF-017-201",
    "idRef": "017-201",
    "slug": "apartamento-edificio-soberano-unidade-201-ref-017",
    "title": "Apartamento 201 no Edifício Soberano",
    "purpose": "locacao",
    "type": "apartamento",
    "city": "Redenção",
    "neighborhood": null,
    "publicLocation": "Próximo à FESAR, Redenção",
    "price": 2000,
    "priceOnRequest": false,
    "priceNote": "Mobiliado",
    "condominiumFee": null,
    "fees": [],
    "conditions": [
      "Itens inclusos e disponibilidade devem ser confirmados no atendimento"
    ],
    "bedrooms": 1,
    "suites": null,
    "bathrooms": null,
    "lavabos": null,
    "parking": null,
    "builtArea": null,
    "landArea": null,
    "landDimensions": null,
    "status": "Disponibilidade sob consulta",
    "featured": false,
    "shortDescription": "Apartamento de um dormitório, mobiliado e equipado para uso residencial.",
    "fullDescription": "Apartamento mobiliado no Edifício Soberano, próximo à FESAR. A configuração inclui sala com sofá, mesa e cadeiras, cozinha equipada, geladeira, cooktop e máquina de lavar, além de cama, guarda-roupa espelhado e ar-condicionado. A relação final dos itens inclusos deve ser confirmada no atendimento.",
    "features": [
      "1 dormitório",
      "Mobiliado",
      "Cozinha equipada",
      "Guarda-roupa espelhado"
    ],
    "amenities": [
      "Ar-condicionado",
      "Geladeira",
      "Cooktop",
      "Máquina de lavar",
      "Sofá",
      "Mesa e cadeiras",
      "Cama"
    ],
    "documents": [],
    "financeable": null,
    "furnished": true,
    "publishedAt": "2026-08-08"
  },
  {
    "id": "REF-013-014",
    "idRef": "013",
    "slug": "sala-comercial-galeria-sanches-ref-013-014",
    "title": "Sala comercial na Galeria Sanches",
    "purpose": "locacao",
    "type": "sala",
    "city": "Redenção",
    "neighborhood": "Galeria Sanches",
    "publicLocation": "Galeria Sanches, Redenção",
    "price": 3500,
    "priceOnRequest": false,
    "priceNote": null,
    "condominiumFee": null,
    "fees": [],
    "conditions": [],
    "bedrooms": null,
    "suites": null,
    "bathrooms": null,
    "lavabos": null,
    "parking": null,
    "builtArea": null,
    "landArea": null,
    "landDimensions": null,
    "status": "Disponibilidade sob consulta",
    "featured": false,
    "shortDescription": "Sala comercial com fachada envidraçada e espaço interno alongado.",
    "fullDescription": "Sala comercial com fachada amplamente envidraçada, favorecendo a entrada de luz e a exposição do espaço. O ambiente principal é alongado e possui uma divisão menor de apoio nos fundos, além de banheiro e ponto com pia. A configuração permite adaptação para diferentes atividades comerciais e de atendimento.",
    "features": [
      "Fachada envidraçada",
      "Ambiente principal alongado",
      "Área de apoio nos fundos",
      "Banheiro",
      "Ponto com pia"
    ],
    "amenities": [],
    "documents": [],
    "financeable": null,
    "furnished": null,
    "publishedAt": "2026-08-08"
  },
  {
    "id": "REF-015",
    "idRef": "015",
    "slug": "ponto-comercial-hospital-sao-vicente-ref-015",
    "title": "Ponto comercial ao lado do Hospital São Vicente",
    "purpose": "locacao",
    "type": "ponto-comercial",
    "city": "Redenção",
    "neighborhood": null,
    "publicLocation": "Rua Dr. Pedro Paulo Barcauí, ao lado do Hospital São Vicente, Redenção",
    "price": 3000,
    "priceOnRequest": false,
    "priceNote": null,
    "condominiumFee": null,
    "fees": [],
    "conditions": [],
    "bedrooms": null,
    "suites": null,
    "bathrooms": null,
    "lavabos": null,
    "parking": null,
    "builtArea": null,
    "landArea": null,
    "landDimensions": null,
    "status": "Disponibilidade sob consulta",
    "featured": false,
    "shortDescription": "Ponto comercial com fachada de vidro e ambientes divididos.",
    "fullDescription": "Ponto comercial térreo com fachada de vidro e referência pública ao lado do Hospital São Vicente. A entrada leva a um salão de recepção, seguido por corredor com divisões internas. O imóvel também possui copa ou cozinha, banheiro de apoio e acesso lateral.",
    "features": [
      "Fachada de vidro",
      "Recepção ou salão",
      "Corredor com divisões internas",
      "Copa ou cozinha",
      "Banheiro",
      "Acesso lateral"
    ],
    "amenities": [],
    "documents": [],
    "financeable": null,
    "furnished": null,
    "publishedAt": "2026-08-08"
  },
  {
    "id": "REF-011-018-019",
    "idRef": "011",
    "slug": "casa-condominio-rio-pison-ref-011-018-019",
    "title": "Casa com piscina no Condomínio Rio Pison",
    "purpose": "venda",
    "type": "casa",
    "city": "Redenção",
    "neighborhood": "Condomínio Rio Pison",
    "publicLocation": "Condomínio Rio Pison, Redenção",
    "price": null,
    "priceOnRequest": true,
    "priceNote": "Valor sob consulta",
    "condominiumFee": null,
    "fees": [],
    "conditions": [],
    "bedrooms": null,
    "suites": null,
    "bathrooms": null,
    "lavabos": null,
    "parking": null,
    "builtArea": null,
    "landArea": null,
    "landDimensions": null,
    "status": "Disponibilidade sob consulta",
    "featured": false,
    "shortDescription": "Sobrado contemporâneo com piscina, cozinha com ilha e amplos planos de vidro.",
    "fullDescription": "Sobrado contemporâneo com fachada de linhas retas, grandes planos de vidro e detalhes amadeirados. A área social valoriza a amplitude e a entrada de luz, enquanto a cozinha reúne ilha central e marcenaria planejada. Nos fundos, a piscina privativa e a área externa compõem o espaço de lazer.",
    "features": [
      "Sobrado contemporâneo",
      "Área social ampla",
      "Grandes planos de vidro",
      "Cozinha com ilha central",
      "Marcenaria planejada"
    ],
    "amenities": [
      "Piscina privativa",
      "Paisagismo",
      "Iluminação embutida e linear"
    ],
    "documents": [],
    "financeable": null,
    "furnished": null,
    "publishedAt": "2026-08-08"
  },
  {
    "id": "REF-038",
    "idRef": "038",
    "slug": "casa-pacos-de-opala-portfolio-ref-038",
    "title": "Casa no Residencial Paços de Opala",
    "purpose": "locacao",
    "type": "casa",
    "city": "Redenção",
    "neighborhood": "Residencial Paços de Opala",
    "publicLocation": "Residencial Paços de Opala, Redenção",
    "price": null,
    "priceOnRequest": false,
    "priceNote": "Imóvel já alugado",
    "condominiumFee": null,
    "fees": [],
    "conditions": [],
    "bedrooms": 2,
    "suites": 1,
    "bathrooms": null,
    "lavabos": null,
    "parking": null,
    "builtArea": null,
    "landArea": null,
    "landDimensions": null,
    "status": "Indisponível",
    "featured": false,
    "shortDescription": "Imóvel de portfólio com suíte, dois quartos e espaço gourmet.",
    "fullDescription": "Casa contemporânea apresentada como imóvel de portfólio e atualmente indisponível. A configuração inclui uma suíte com closet, dois quartos, banheiro social, cozinha interna com cooktop e cozinha externa com churrasqueira. A área de serviço e os ambientes claros complementam a distribuição da residência.",
    "features": [
      "1 suíte com closet",
      "2 quartos",
      "Banheiro social",
      "Cozinha interna com cooktop",
      "Cozinha externa",
      "Lavanderia"
    ],
    "amenities": [
      "Espaço gourmet",
      "Churrasqueira"
    ],
    "documents": [],
    "financeable": null,
    "furnished": null,
    "publishedAt": "2026-08-08"
  }
];

export const properties = listingRecords.map((property) => ({
  ...property,
  mainImage: propertyMedia[property.id][0],
  gallery: propertyMedia[property.id],
}));

export const typeLabels = {
  casa: "Casa",
  apartamento: "Apartamento",
  lote: "Lote",
  sala: "Sala comercial",
  "ponto-comercial": "Ponto comercial",
};

export const purposeLabels = {
  venda: "Venda",
  locacao: "Locação",
};
